### ISSUE TITLE
扫描提示服务中断

### ISSUE THREAD

**Issue by 5icorgi** [gobysec/Goby#181]
系统版本：Win10 1909
npcap：0.9995
![1.jpg](https://i.loli.net/2021/02/07/wD9vQc2ZLKoqJyl.jpg)
```
2021/02/07 20:04:16 Grab version:  grab_version_1.7.1.1
2021/02/07 20:04:16 Support 289  protocols, 701  ports
2021/02/07 20:04:16 Version: v1.26.276+beta
2021/02/07 20:04:16 API Server listen at  127.0.0.1:8361
2021/02/07 20:04:16 127.0.0.1:57324   GET   /api/v1/live  
2021/02/07 20:04:16 127.0.0.1:57325   GET   /api/v1/version  
2021/02/07 20:04:17 127.0.0.1:57326   GET   /api/v1/getEnvi?  
2021/02/07 20:04:17 127.0.0.1:57327   GET   /api/v1/tasks  
2021/02/07 20:04:18 [DEBUG] device name is not match: \Device\NPF_{911043CE-89C1-4C12-9EA9-08037116BB4D} != \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2}
2021/02/07 20:04:18 [DEBUG] getGatewayMac: \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2} 0.0.0.0
2021/02/07 20:04:19 find router mac is  fc:7c:02:e5:fe:18
2021/02/07 20:04:19 [DEBUG] fetch mac address: \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2} fc:7c:02:e5:fe:18
2021/02/07 20:04:21 127.0.0.1:57331   POST   /api/v1/getStatisticsData  
2021/02/07 20:04:22 127.0.0.1:57332   POST   /api/v1/resumeScan  
2021/02/07 20:04:22 scan  1-65535 112.48.134.0/24
2021/02/07 20:04:22 127.0.0.1:57333   POST   /api/v1/getProgress  
2021/02/07 20:04:23 found device from route table: \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2}
2021/02/07 20:04:23 [DEBUG] device name is not match: \Device\NPF_{911043CE-89C1-4C12-9EA9-08037116BB4D} != \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2}
2021/02/07 20:04:23 [DEBUG] getGatewayMac: \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2} 112.48.134.0
2021/02/07 20:04:24 find router mac is  fc:7c:02:e5:fe:18
2021/02/07 20:04:24 [DEBUG] fetch mac address: \Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2} fc:7c:02:e5:fe:18
2021/02/07 20:04:24 select adapter of to send packets:  &{\Device\NPF_{530A9F23-B000-499F-8DA8-AA774CD43CF2} 192.168.123.114 {192.168.123.114 ffffff00} ffffff00 e0:d5:5e:b4:ac:bb Realtek Gaming GbE Family Controller fc:7c:02:e5:fe:18}
Starting to read packets
2021/02/07 20:04:25 GrabScannerStatistics: {0 0 0 1}
2021/02/07 20:04:25 AppScannerStatistics: {0 0 0 1}
2021/02/07 20:04:25 SendPacketCount: 726 16776960
2021/02/07 20:04:25 127.0.0.1:57335   POST   /api/v1/getProgress  
2021/02/07 20:04:26 SendPacketCount: 822 16776960
2021/02/07 20:04:27 SendPacketCount: 918 16776960
2021/02/07 20:04:27 [WARNING] ipv6 is not support now! [fe80::211:32ff:fe7b:8cf%以太网]
2021/02/07 20:04:27 [WARNING] ipv6 is not support now! [fe80::a650:46ff:fedc:14e1%以太网]
2021/02/07 20:04:28 SendPacketCount: 1014 16776960
2021/02/07 20:04:28 127.0.0.1:57337   POST   /api/v1/getProgress  
2021/02/07 20:04:29 SendPacketCount: 1108 16776960
2021/02/07 20:04:30 SendPacketCount: 1204 16776960
2021/02/07 20:04:31 SendPacketCount: 1300 16776960
2021/02/07 20:04:31 127.0.0.1:57340   POST   /api/v1/getProgress  
2021/02/07 20:04:32 SendPacketCount: 1395 16776960
2021/02/07 20:04:32 BasicNetworkInfoScanner out...
panic: runtime error: index out of range [3] with length 0

goroutine 89 [running]:
encoding/binary.bigEndian.Uint32(...)
	encoding/binary/binary.go:112
git.gobies.org/goby/portscanner.ip2int(0x0, 0x0, 0x0, 0x0)
	git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner_base.go:49 +0x58
git.gobies.org/goby/portscanner.IP2Int(0xc002168a64, 0x5, 0x1f82db3)
	git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner_base.go:53 +0x80
git.gobies.org/goby/portscanner.(*PortScanner).IsValidHost(0xc0008a9c40, 0xc002168a64, 0x5, 0xc0013d1e80)
	git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner_base.go:71 +0xf0
git.gobies.org/goby/goby.(*GobyScanner).StartBasicNetworkInfoScanner(0xc000084a80, 0xc00140da24)
	git.gobies.org/goby/goby/goby_basic_network_scanner.go:73 +0x22b
created by git.gobies.org/goby/goby.(*GobyScanner).basicNetworkInfoTask.func1
	git.gobies.org/goby/goby/goby_tasks.go:79 +0x4f
```

**Comment by gobysec** [comment]
Goby暂不支持ipv6，获取ipv6提示了报错信息。
