### ISSUE TITLE
服务中断，一直重启服务

### ISSUE THREAD

**Issue by qimingstar** [gobysec/Goby#226]
goby版本：内测版linux-1.8.268
操作环境: deepin系统20.2社区版
错误信息:
2021/05/02 20:51:11 SendPacketCount: 736 1672
2021/05/02 20:51:11 BasicNetworkInfoScanner out...
panic: runtime error: index out of range [3] with length 0

goroutine 111 [running]:
encoding/binary.bigEndian.Uint32(...)
	encoding/binary/binary.go:112
git.gobies.org/goby/portscanner.ip2int(0x0, 0x0, 0x0, 0x0)
	git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner_base.go:59 +0x58
git.gobies.org/goby/portscanner.IP2Int(0xc00417f5d0, 0x5, 0x32d0b58)
	git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner_base.go:63 +0x87
git.gobies.org/goby/portscanner.(*PortScanner).IsValidHost(0xc003028230, 0xc00417f5d0, 0x5, 0xc002735de0)
	git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner_base.go:81 +0x6e
git.gobies.org/goby/goby.(*GobyScanner).StartBasicNetworkInfoScanner(0xc002ec0a80, 0xc001ad4fa0)
	git.gobies.org/goby/goby/goby_basic_network_scanner.go:73 +0x22c
created by git.gobies.org/goby/goby.(*GobyScanner).basicNetworkInfoTask.func1
	git.gobies.org/goby/goby/goby_tasks.go:79 +0x48
错误截图![c985373b7b38924d028ccb7a76bfb48](https://user-images.githubusercontent.com/44332676/116813807-47985680-ab88-11eb-8fd3-d046950e7e85.png)

**Comment by qimingstar** [comment]
Deepin系统问题，升级到最近版本已经修复
