### ISSUE TITLE
发现 未知错误

### ISSUE THREAD

**Issue by maomaojzb** [gobysec/Goby#404]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2023/03/09 16:24:44 read user rule file ok: 0
2023/03/09 16:24:44 Version: v2.0.312+alpha
2023/03/09 16:24:45 API Server listen at 127.0.0.1:8361
2023/03/09 16:24:46 127.0.0.1:52184 GET /api/v1/live
2023/03/09 16:24:53 127.0.0.1:52205 POST /api/v1/setEnvi
2023/03/09 16:24:53 127.0.0.1:52207 POST /api/v1/getTasks
2023/03/09 16:24:53 127.0.0.1:52206 GET /api/v1/getEnvi?
2023/03/09 16:24:54 [DEBUG] get adapter of device
2023/03/09 16:24:54 [DEBUG] devices: [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 []}]
2023/03/09 16:24:54 [ERROR] could not find any network interface.
2023/03/09 16:24:54 interface conversion: string is not error: missing method Error
2023/03/09 16:24:54 interface conversion: string is not error: missing method Error goroutine 14 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
git.gobies.org/goby/goby/api.getEnviHandler.func1()
git.gobies.org/goby/goby/api/getEnvi.go:169 +0x14c
panic({0x141fd24e0, 0xc0032f0d20})
runtime/panic.go:838 +0x207
git.gobies.org/goby/goby/api.pcapInfo.func1()
git.gobies.org/goby/goby/api/getEnvi.go:33 +0x45
panic({0x141ed4680, 0x1433c0480})
runtime/panic.go:838 +0x207
git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:349 +0x205
git.gobies.org/goby/portscanner/pcapsend.GetAdpaterInfo({0x0?, 0x1a0a28?})
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:355 +0x25
git.gobies.org/goby/goby/api.pcapInfo({0x0?, 0x78?})
git.gobies.org/goby/goby/api/getEnvi.go:42 +0x7c
git.gobies.org/goby/goby/api.envField({0x0?, 0xc0053b7cb0?}, {0x1422f29d3?, 0x9?})
git.gobies.org/goby/goby/api/getEnvi.go:73 +0x385
git.gobies.org/goby/goby/api.getEnviFields({0x0, 0x0}, {0xc0033076f0, 0xf, 0x140100d85?})
git.gobies.org/goby/goby/api/getEnvi.go:146 +0xec
git.gobies.org/goby/goby/api.getEnviHandler({0x1433da2b8, 0xc0011c6620}, 0xc000bb6000?)
git.gobies.org/goby/goby/api/getEnvi.go:181 +0x2fd
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.basicAuth.func1({0x1433da2b8?, 0xc0011c6620?}, 0x88?)
git.gobies.org/goby/goby/api/api.go:121 +0x248
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.logHttpRequest.func1({0x1433da2b8, 0xc0011c6620}, 0xc003176600)
git.gobies.org/goby/goby/api/api.go:104 +0x1f4
net/http.HandlerFunc.ServeHTTP(0xc003176500?, {0x1433da2b8?, 0xc0011c6620?}, 0x0?)
net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0032723c0, {0x1433da2b8, 0xc0011c6620}, 0xc00015e200)
github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc0053b6240?}, {0x1433da2b8, 0xc0011c6620}, 0xc00015e200)
net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0023a00a0, {0x1433db788, 0xc0053b6150})
net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
net/http/server.go:3071 +0x4db
2023/03/09 16:25:02 127.0.0.1:52231 POST /api/v1/getStatisticsData
2023/03/09 16:25:04 127.0.0.1:52238 POST /api/v1/resumeScan
2023/03/09 16:25:04 scan 21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 202.207.126.56
2023/03/09 16:25:04 start port scanner: totalSize: 90, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1678350075480295100, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 0
2023/03/09 16:25:04 pcap version: Npcap version 0.9983, based on libpcap version 1.9.1-PRE-GIT
2023/03/09 16:25:04 127.0.0.1:52239 POST /api/v1/getProgress
2023/03/09 16:25:04 found device from route table for 202.207.126.56:
2023/03/09 16:25:04 [DEBUG] get adapter of device
2023/03/09 16:25:04 [DEBUG] devices: [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 []}]
2023/03/09 16:25:04 [ERROR] could not find any network interface.
panic: could not find any network interface.
goroutine 32 [running]:
git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:349 +0x205
git.gobies.org/goby/portscanner/pcapsend.NewPcapSender(0xc00016e2c0, 0xc003d001e0, 0xc003d00230)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:95 +0x23e
git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan(0xc00260fc00, {0x1433db6e0?, 0xc005d34d40}, 0xc00257bfd0?, 0xc000e6dd40, 0xc000e6dda0)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner.go:183 +0x88
created by git.gobies.org/goby/portscanner.(*PortScanner).Start
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner.go:232 +0x595

**Comment by why-git-why** [comment]
看其他回答，我和你的问题一样，安装个1.6版本的npcap就解决了，https://nmap.org/npcap/dist/
