### ISSUE TITLE
An unknown error occurs

### ISSUE THREAD

**Issue by w1ndyyyy** [gobysec/Goby#413]
2023/04/15 19:42:06 read user rule file ok: 0
2023/04/15 19:42:06 Version: v2.0.320 beta
2023/04/15 19:42:07 API Server listen at  127.0.0.1:8361
2023/04/15 19:42:07 127.0.0.1:12067   GET   /api/v1/live  
2023/04/15 19:42:08 127.0.0.1:12068   POST   /api/v1/setEnvi  
2023/04/15 19:42:08 127.0.0.1:12071   GET   /api/v1/getEnvi?field=chromePath,dataIntegrity,datadir,dir,midKey,proxyServer,userRuleSize,vulVersion  
2023/04/15 19:42:08 127.0.0.1:12072   GET   /api/v1/getEnvi?field=ip  
2023/04/15 19:42:08 127.0.0.1:12073   GET   /api/v1/getEnvi?field=gid,key,godserver  
2023/04/15 19:42:08 127.0.0.1:12074   POST   /api/v1/getPOCList  
2023/04/15 19:42:08 127.0.0.1:12077   POST   /api/v1/getTasks  
2023/04/15 19:42:08 127.0.0.1:12078   GET   /api/v1/getEnvi?field=licenseInfo,midKey  
2023/04/15 19:42:08 [DEBUG] get adapter of device \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] devices:  [{\Device\NPF_{8A9D717F-158B-4E21-894C-0BE11DAE555E} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{3F9E679F-B90C-4DE2-8F77-4848CFF260A5} WAN Miniport (IPv6) 22 []} {\Device\NPF_{8D3F0990-3994-47CE-9E2D-1FA48D0AE1FC} WAN Miniport (IP) 22 []} {\Device\NPF_{878619E0-C6DC-4466-B350-958BF5C5BD3C} Realtek 8822BE Wireless LAN 802.11ac PCI-E NIC 30 [{fe80::aa7:f04c:f85a:fac0 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.0.105 ffffff00 192.168.0.255 <nil>}]} {\Device\NPF_{69DB712B-F064-4F24-AC3F-9814E89E501D} VMware Virtual Ethernet Adapter for VMnet8 22 [{fe80::16dc:da55:21f1:ca6c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.1.1 ffffff00 192.168.1.255 <nil>}]} {\Device\NPF_{95103576-5D7A-400E-88E7-5DCB97ED4E81} VMware Virtual Ethernet Adapter for VMnet1 22 [{fe80::1e26:a823:e24e:9601 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.86.1 ffffff00 192.168.86.255 <nil>}]} {\Device\NPF_{7EEC5F53-2635-4DD7-87C8-8AC722A41AA9} Microsoft Wi-Fi Direct Virtual Adapter #4 46 [{fe80::e71c:90d2:9352:a752 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {123.123.123.123 ff000000 123.255.255.255 <nil>}]} {\Device\NPF_{E8B2DA82-962C-4297-8D7B-FA4C257A03C5} Microsoft Wi-Fi Direct Virtual Adapter #3 46 [{fe80::2574:96d2:ebb1:9b0c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.142.249 ffff0000 169.254.255.255 <nil>}]} {\Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} Clash Tunnel 22 [{198.18.0.1 ffff0000 198.18.255.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 []}]
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{8A9D717F-158B-4E21-894C-0BE11DAE555E} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{3F9E679F-B90C-4DE2-8F77-4848CFF260A5} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{8D3F0990-3994-47CE-9E2D-1FA48D0AE1FC} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{878619E0-C6DC-4466-B350-958BF5C5BD3C} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{69DB712B-F064-4F24-AC3F-9814E89E501D} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{95103576-5D7A-400E-88E7-5DCB97ED4E81} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{7EEC5F53-2635-4DD7-87C8-8AC722A41AA9} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] device name is not match: \Device\NPF_{E8B2DA82-962C-4297-8D7B-FA4C257A03C5} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:42:08 [DEBUG] getGatewayMac: \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} 0.0.0.0
2023/04/15 19:42:09 find router mac is  45:00:00:1f:ff:4a
2023/04/15 19:42:09 [DEBUG] fetch mac address: \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} 45:00:00:1f:ff:4a
2023/04/15 19:42:09 [DEBUG] close pcap handler for getGatewayMac
2023/04/15 19:42:14 127.0.0.1:12082   GET   /api/v1/listAdapters  
2023/04/15 19:46:11 127.0.0.1:12269   GET   /api/v1/listAdapters  
2023/04/15 19:46:20 127.0.0.1:12272   POST   /api/v1/checkProxy  
2023/04/15 19:46:24 127.0.0.1:12279   POST   /api/v1/setEnvi  
2023/04/15 19:46:24 127.0.0.1:12280   POST   /api/v1/checkProxy  
2023/04/15 19:47:41 127.0.0.1:12377   POST   /api/v1/getTasks  
2023/04/15 19:47:58 127.0.0.1:12380   POST   /api/v1/getTasks  
2023/04/15 19:48:14 127.0.0.1:12387   POST   /api/v1/getTasks  
2023/04/15 19:48:23 127.0.0.1:12390   POST   /api/v1/deleteTask  
2023/04/15 19:48:23 127.0.0.1:12391   POST   /api/v1/getTasks  
2023/04/15 19:48:26 127.0.0.1:12392   POST   /api/v1/deleteTask  
2023/04/15 19:48:26 127.0.0.1:12393   POST   /api/v1/getTasks  
2023/04/15 19:48:28 127.0.0.1:12394   POST   /api/v1/deleteTask  
2023/04/15 19:48:28 127.0.0.1:12395   POST   /api/v1/getTasks  
2023/04/15 19:48:39 127.0.0.1:12424   POST   /api/v1/deleteTask  
2023/04/15 19:48:39 127.0.0.1:12425   POST   /api/v1/getTasks  
2023/04/15 19:48:43 127.0.0.1:12430   POST   /api/v1/getPOCList  
2023/04/15 19:48:43 127.0.0.1:12431   GET   /api/v1/getFailedPocs  
2023/04/15 19:48:51 127.0.0.1:12434   POST   /api/v1/getPOCList  
2023/04/15 19:48:51 127.0.0.1:12435   GET   /api/v1/getFailedPocs  
2023/04/15 19:48:54 127.0.0.1:12438   POST   /api/v1/getPOCInfo  
2023/04/15 19:48:59 127.0.0.1:12441   POST   /api/v1/getPOCList  
2023/04/15 19:48:59 127.0.0.1:12442   GET   /api/v1/getFailedPocs  
2023/04/15 19:49:28 127.0.0.1:12451   POST   /api/v1/getTasks  
2023/04/15 19:49:31 127.0.0.1:12454   POST   /api/v1/getPOCList  
2023/04/15 19:49:45 127.0.0.1:12459   POST   /api/v1/startScan  
2023/04/15 19:49:45 [WARNING] change deep-analysis feature is not included in your current license.
2023/04/15 19:49:45 scan  21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 192.168.0.1
2023/04/15 19:49:45 BasicNetworkInfoScanner out...
2023/04/15 19:49:45 start port scanner: totalSize: 91, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1681559385152006300, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
2023/04/15 19:49:45 pcap version: Npcap version 1.60, based on libpcap version 1.10.2-PRE-GIT
2023/04/15 19:49:45 127.0.0.1:12460   POST   /api/v1/getProgress  
2023/04/15 19:49:45 127.0.0.1:12461   POST   /api/v1/getStatisticsData  
2023/04/15 19:49:45 found device from route table for 192.168.0.1: \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] get adapter of device \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] devices:  [{\Device\NPF_{8A9D717F-158B-4E21-894C-0BE11DAE555E} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{3F9E679F-B90C-4DE2-8F77-4848CFF260A5} WAN Miniport (IPv6) 22 []} {\Device\NPF_{8D3F0990-3994-47CE-9E2D-1FA48D0AE1FC} WAN Miniport (IP) 22 []} {\Device\NPF_{878619E0-C6DC-4466-B350-958BF5C5BD3C} Realtek 8822BE Wireless LAN 802.11ac PCI-E NIC 30 [{fe80::aa7:f04c:f85a:fac0 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.0.105 ffffff00 192.168.0.255 <nil>}]} {\Device\NPF_{69DB712B-F064-4F24-AC3F-9814E89E501D} VMware Virtual Ethernet Adapter for VMnet8 22 [{fe80::16dc:da55:21f1:ca6c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.1.1 ffffff00 192.168.1.255 <nil>}]} {\Device\NPF_{95103576-5D7A-400E-88E7-5DCB97ED4E81} VMware Virtual Ethernet Adapter for VMnet1 22 [{fe80::1e26:a823:e24e:9601 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.86.1 ffffff00 192.168.86.255 <nil>}]} {\Device\NPF_{7EEC5F53-2635-4DD7-87C8-8AC722A41AA9} Microsoft Wi-Fi Direct Virtual Adapter #4 46 [{fe80::e71c:90d2:9352:a752 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {123.123.123.123 ff000000 123.255.255.255 <nil>}]} {\Device\NPF_{E8B2DA82-962C-4297-8D7B-FA4C257A03C5} Microsoft Wi-Fi Direct Virtual Adapter #3 46 [{fe80::2574:96d2:ebb1:9b0c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.142.249 ffff0000 169.254.255.255 <nil>}]} {\Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} Clash Tunnel 22 [{198.18.0.1 ffff0000 198.18.255.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 []}]
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{8A9D717F-158B-4E21-894C-0BE11DAE555E} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{3F9E679F-B90C-4DE2-8F77-4848CFF260A5} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{8D3F0990-3994-47CE-9E2D-1FA48D0AE1FC} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{878619E0-C6DC-4466-B350-958BF5C5BD3C} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{69DB712B-F064-4F24-AC3F-9814E89E501D} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{95103576-5D7A-400E-88E7-5DCB97ED4E81} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{7EEC5F53-2635-4DD7-87C8-8AC722A41AA9} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] device name is not match: \Device\NPF_{E8B2DA82-962C-4297-8D7B-FA4C257A03C5} != \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2023/04/15 19:49:45 [DEBUG] getGatewayMac: \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} 192.168.0.1
2023/04/15 19:49:46 find router mac is  45:00:00:1f:ff:4b
2023/04/15 19:49:47 [DEBUG] fetch mac address: \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} 45:00:00:1f:ff:4b
2023/04/15 19:49:47 [DEBUG] close pcap handler for getGatewayMac
2023/04/15 19:49:47 select adapter of to send packets:  &{\Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} 198.18.0.1 [] {198.18.0.1 ffff0000} ffff0000  Clash Tunnel 45:00:00:1f:ff:4b}
2023/04/15 19:49:47 routine-recv start
2023/04/15 19:49:47 port scanner is ready
2023/04/15 19:49:47 routine-target run out ping target pool 2
2023/04/15 19:49:47 alive range after ping2 (1): 192.168.0.1
2023/04/15 19:49:47 start first round ARP
2023/04/15 19:49:47 first round ARP done
2023/04/15 19:49:48 127.0.0.1:12464   POST   /api/v1/getStatisticsData  
2023/04/15 19:49:48 127.0.0.1:12463   POST   /api/v1/getProgress  
2023/04/15 19:49:48 3.5s  0/91 (0.00% N/A left); send: 0 0.00 pkt/s (0.00 pkt/s avg); recv: 0 0.00 pkt/s (0.00 pkt/s avg)
2023/04/15 19:49:48 start sending packets
2023/04/15 19:49:48 [WARNING] Serialize failed: invalid src MAC: 
2023/04/15 19:49:48 routine-send out
panic: runtime error: index out of range [0] with length 0

goroutine 1239 [running]:
github.com/google/gopacket/pcap.(*Handle).pcapSendpacket(0xc0041c8f80?, {0x0?, 0x1f?, 0x0?})
	github.com/google/gopacket@v1.1.20-0.20210429153827-3eaba0894325/pcap/pcap_windows.go:658 +0x76
github.com/google/gopacket/pcap.(*Handle).WritePacketData(...)
	github.com/google/gopacket@v1.1.20-0.20210429153827-3eaba0894325/pcap/pcap.go:696
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).sendUDP(0xc00443fd40, 0xc0a80001, 0x8438)
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/pcapsend/send.go:1141 +0x20f
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).SendPackets(0xc00443fd40, {0x37ea310, 0xc000cff500}, 0x0?, 0x0?)
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/pcapsend/send.go:1637 +0x725
created by git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/portscanner.go:209 +0x26f

**Comment by gobysec** [comment]
已收到您的反馈，我们尽快优化，优化后会向您致谢，您可以联系微信号：gobyteam，感谢您对Goby喜爱与支持~
