### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2328956238** [gobysec/Goby#458]
goroutine 11672 [running]:
git.gobies.org/goby/goby.(*GobyScanner).grabUrl(0xc00846e000, 0xc0074a6540, {0x0, 0x0})
	git.gobies.org/goby/goby/goby_grab_scanner.go:356 +0x134
git.gobies.org/goby/goby.(*GobyScanner).grabWeb(0x0?, 0xc00024fce0?)
	git.gobies.org/goby/goby/goby_grab_scanner.go:456 +0x17c
git.gobies.org/goby/goby.(*GobyScanner).addService(0xc00846e000, 0xc00024fce0, 0xc001fa6600)
	git.gobies.org/goby/goby/goby_grab_scanner.go:539 +0x185
git.gobies.org/goby/goby.(*GobyScanner).grabService(0xc00846e000, 0xc00024fce0)
	git.gobies.org/goby/goby/goby_grab_scanner.go:588 +0x3c8
git.gobies.org/goby/goby.(*GobyScanner).StartGrabScanner.func2(0xc000ec19e0?)
	git.gobies.org/goby/goby/goby_grab_scanner.go:637 +0x22c
created by git.gobies.org/goby/goby.(*GobyScanner).StartGrabScanner
	git.gobies.org/goby/goby/goby_grab_scanner.go:628 +0xd3

**Comment by gobysec** [comment]
您可以联系微信号：gobyteam发送一下您详细日志，为您定位问题
