### ISSUE TITLE
goby经常性报错

### ISSUE THREAD

**Issue by laohuan12138** [gobysec/Goby#461]
相关报错代码,
```
警告

发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2023/09/11 19:39:42 [DEBUG] runtime.NumCPU():12, runtime.GOMAXPROCS():10
2023/09/11 19:39:42 read user rule file ok: 0
2023/09/11 19:39:42 common config info honeypot: 0 rabbish: 0 rabbish-md5: 0
2023/09/11 19:39:42 init repleace log regex len: 3
2023/09/11 19:39:42 Grab version: grab_version_1.9.1.0
2023/09/11 19:39:42 Support 344 protocols, 804 ports
2023/09/11 19:39:42 Version: v2.7.4
2023/09/11 19:39:43 API Server listen at 127.0.0.1:8361
2023/09/11 19:39:44 pcap version: Npcap version 1.60, based on libpcap version 1.10.2-PRE-GIT
```
```
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1873298]
goroutine 227 [running]:
git.gobies.org/goby/goby/web.ExtractInternalLinks(0xc00476fce0, {0xc005036380, 0xd42, 0xd80})
git.gobies.org/goby/goby/web/crawler.go:411 +0x3f8
git.gobies.org/goby/goby.(*GobyScanner).AddGrab(0xc000092480, 0xc0090620c0, {0xc004df5050, 0xe}, {0xc005172a00, 0x141b}, 0x1)
git.gobies.org/goby/goby/goby_grab_scanner.go:117 +0x6d0
git.gobies.org/goby/goby.(*GobyScanner).grabUrl(0xc000092480, 0xc0056de1c0, {0xc004df5050, 0xe})
git.gobies.org/goby/goby/goby_grab_scanner.go:373 +0x35e
git.gobies.org/goby/goby.(*GobyScanner).visitHttpBindHost(0xc000092480, {0xc004df5050, 0xe}, {0x2758525, 0x2}, {0xc004d8e720, 0x7})
git.gobies.org/goby/goby/goby_grab_scanner.go:488 +0x335
git.gobies.org/goby/goby.(*GobyScanner).grabWeb(0x0?, 0xc005101e60?)
git.gobies.org/goby/goby/goby_grab_scanner.go:460 +0x1a5
git.gobies.org/goby/goby.(*GobyScanner).addService(0xc000092480, 0xc005101e60, 0xc008a3d500)
git.gobies.org/goby/goby/goby_grab_scanner.go:540 +0x185
git.gobies.org/goby/goby.(*GobyScanner).grabService(0xc000092480, 0xc005101e60)
git.gobies.org/goby/goby/goby_grab_scanner.go:589 +0x3c8
git.gobies.org/goby/goby.(*GobyScanner).StartGrabScanner.func2(0xc8000000c80?)
git.gobies.org/goby/goby/goby_grab_scanner.go:638 +0x22c
created by git.gobies.org/goby/goby.(*GobyScanner).StartGrabScanner
git.gobies.org/goby/goby/goby_grab_scanner.go:629 +0xd3
```

**Comment by gobysec** [comment]
此问题已修复，已在最新版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
