### ISSUE TITLE
nohup 重定向日志后台启动

### ISSUE THREAD

**Issue by dingafter** [gobysec/Goby#505]
界面执行命令启动正常，客户端正常链接，
使用nohup命令重定向日志启动
nohup ./goby-cmd-linux -apiauth user:pass -mode api -bind 0.0.0.0:8361 >./runlog.log 2>&1 &
启动失败
2024/06/21 15:15:22 [ERROR] API Server exit: listen tcp: lookup tcp/7833 : Unrecognized service
2024/06/21 15:15:22 [StartService ERROR] {content："server bind failed", errCode: 0}
panic: listen tcp: lookup tcp/7833 : Unrecognized service

goroutine 9 [running]:
git.gobies.org/goby/goby/api.StartAPIServer.func1()
	git.gobies.org/goby/goby/api/api.go:352 +0x1ad
created by git.gobies.org/goby/goby/api.StartAPIServer in goroutine 1
	git.gobies.org/goby/goby/api/api.go:338 +0x179

**Comment by dingafter** [comment]
![image](https://github.com/gobysec/Goby/assets/32186147/0114ab79-3859-44a4-ac26-1724b9693ee1)

**Comment by dingafter** [comment]
goby 2.9.5
CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.92.1.el7.x86_64
