### ISSUE TITLE
无法扫描，一直卡在1% panic: could not find any network interface.

### ISSUE THREAD

**Issue by Pisces032** [gobysec/Goby#512]
网卡不能选择，只有Auto一个选项
Npcap装了最新版不行，重装1.6也不行
重启也没用
更改socket代理扫描也没用

```
2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{C2AAC7C9-2281-443E-B453-AED28ACDBD8A} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{ACFFCDF3-2124-498F-B002-F9CACAB1E6FC} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{D16F1AA1-5BB3-4555-AD13-BDD2584FA987} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{659B2433-4081-497A-B739-348D6E872097} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{1187BD45-CCA8-4EE7-B991-8A75F6E20D0A} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{9D7F34F9-F612-42A2-AAB9-452F6CFB389F} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{3D292E9D-03B2-4AEF-9AF3-18B7FCD59409} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] device name is not match: \Device\NPF_{912066C0-E3E4-4594-84EB-ABDC5D8D27BC} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:49 [DEBUG] getGatewayMac: \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052} 255.255.255.224

2024/08/29 17:08:50 [WARNING] send UDP to 255.255.255.224:65321 error: dial udp 255.255.255.224:65321: connect: A socket operation was attempted to an unreachable network.

2024/08/29 17:08:50 find router mac is 00:1a:a9:17:89:57

2024/08/29 17:08:50 [DEBUG] close pcap handler for getGatewayMac

2024/08/29 17:08:50 [DEBUG] device name is not match: \Device\NPF_{F2D4C9EC-15AA-43DA-85D5-5FAF11A7A9AB} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [DEBUG] device name is not match: \Device\NPF_Loopback != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [DEBUG] device name is not match: \Device\NPF_{E03226E6-984F-4B1A-B09C-A03AFD7CC518} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [DEBUG] device name is not match: \Device\NPF_{CDBC69FE-A64A-40A5-87D7-2DBA1D230F9B} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [DEBUG] device name is not match: \Device\NPF_{0CFFAB93-F0BB-495E-9A2D-E246B0516C6B} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [DEBUG] device name is not match: \Device\NPF_{D2C533FE-01FA-4E03-8749-1ED28F8A82B9} != \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [ERROR] could not find any network interface. \Device\NPF_{3DE5FFB3-FD0D-4E79-962A-4B67D6C27052}

2024/08/29 17:08:50 [ERROR] NewPcapSender failed: could not find any network interface.

panic: could not find any network interface.

goroutine 547 [running]:

git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan(0xc003c22b60, {0x7ff62614c480?, 0xc00b0060f0}, 0x0?, 0xc002716180, 0xc0027161e0)

git.gobies.org/goby/portscanner@v0.0.7/portscanner.go:207 +0x40f

created by git.gobies.org/goby/portscanner.(*PortScanner).Start in goroutine 132

git.gobies.org/goby/portscanner@v0.0.7/portscanner.go:253 +0x5c9
```

**Comment by gobysec** [comment]
您好，可以联系我们的微信在线客服帮您排查解决：gobyteam
